# Generated by Django 3.1 on 2020-08-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPoll', '0002_remove_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='voteTotal',
            field=models.IntegerField(default=0),
        ),
    ]
